### ISSUE TITLE
大哥，给个apk的下载啊，云盘什么的都可以，导入失败的

### ISSUE THREAD

**Issue by wudaotiantian** [donal-tong/Tut-android#1]
Error:Execution failed for task ':apptu:validateSigningDdDebug'.
> Keystore file F:\project\test\MyApplication\apptu\Users\Donal\Dropbox\Vikaa\vikaa.key not found for signing config 'releaseConfig'.

**Comment by DLTech21** [comment]
http://fir.im/1csn

**Comment by wudaotiantian** [comment]
ok,what's the problem?

**Comment by wudaotiantian** [comment]
flashback in huawei 5c
